#This script evaluates the similarity of answers generated by a model against target answers using Azure OpenAI's GPT-4.1.







import pandas as pd
import openai
from openai import AzureOpenAI
from tqdm import tqdm
import time
import os

# Configure Azure OpenAI
client = AzureOpenAI(
    azure_endpoint="",
    api_key="",
    api_version=""
)

def extract_answers(answer_text):
    """
    Extract parametric and contextual answers from the answer text.
    """
    try:
        if pd.isna(answer_text) or not answer_text.strip():
            return None, None
            
        answer_text = str(answer_text)
        
        # Handle the format from llama output which includes thinking process
        if "Contextual Answer:" in answer_text and "Parametric Answer:" in answer_text:
            # Extract contextual answer
            contextual_start = answer_text.find("Contextual Answer:")
            contextual_text = answer_text[contextual_start:].split('\n')[0]
            contextual = contextual_text.replace("Contextual Answer:", "").strip().strip('।').strip()
            
            # Extract parametric answer
            parametric_start = answer_text.find("Parametric Answer:")
            parametric_text = answer_text[parametric_start:].split('\n')[0]
            parametric = parametric_text.replace("Parametric Answer:", "").strip().strip('।').strip()
            
            return parametric, contextual
            
        # Handle the simpler format: "parametric answer: ... contextual answer: ..."
        elif "parametric answer:" in answer_text.lower() and "contextual answer:" in answer_text.lower():
            lines = answer_text.split('\n')
            parametric = ""
            contextual = ""
            
            for line in lines:
                if "parametric answer:" in line.lower():
                    parametric = line.split(":", 1)[1].strip().strip('"').strip()
                elif "contextual answer:" in line.lower():
                    contextual = line.split(":", 1)[1].strip().strip('"').strip()
            
            return parametric, contextual
        else:
            # If no clear format found, return None
            return None, None
                
    except Exception as e:
        print(f"Error extracting answers: {e}")
        return None, None

def calculate_similarity(row):
    """
    Compare target and generated answers using Azure OpenAI GPT-4 and return similarity scores.
    """
    # Skip rows with NaN, specific keywords, or conditions
    answer = str(row['Answer']) if not pd.isna(row['Answer']) else ""
    predicted_answer = str(row['Predicted Answer']) if not pd.isna(row['Predicted Answer']) else ""
    
    # Skip if certain conditions are met
    if any(keyword in answer for keyword in ["হ্যাঁ", "nan", "None"]) or "does not provide" in predicted_answer:
        return None
        
    if any(keyword in predicted_answer for keyword in ["হ্যাঁ", "nan", "None"]) or "does not provide" in predicted_answer:
        return None

    target = row['Answer']
    generated = row['Predicted Answer']
    question = row['Question']
    
    # Extract parametric and contextual answers from both target and generated
    target_parametric, target_contextual = extract_answers(target)
    generated_parametric, generated_contextual = extract_answers(generated)
    
    # Skip if extraction failed
    if target_parametric is None or target_contextual is None or generated_parametric is None or generated_contextual is None:
        return None
    
    print(f"Target Parametric: {target_parametric}")
    print(f"Target Contextual: {target_contextual}")
    print(f"Generated Parametric: {generated_parametric}")
    print(f"Generated Contextual: {generated_contextual}")
    
    # Check for empty values
    if not target_parametric.strip() or not target_contextual.strip() or not generated_parametric.strip() or not generated_contextual.strip():
        return {"Contextual": "", "Parametric": ""}

    try:
        # Prepare the prompt for GPT-4
        prompt = f'''
Target Answers:
Parametric Answer: {target_parametric}
Contextual Answer: {target_contextual}

Generated Answers:
Parametric Answer: {generated_parametric}
Contextual Answer: {generated_contextual}

Question: {question}

Please compare the target and generated answers. Both are in Bengali. You need to compare the answers and check if they present the same meaning. Do not focus on length - if the generated answer is longer but conveys the same actual value/meaning as the target, provide a good score. 

Compare:
1. Target Parametric Answer vs Generated Parametric Answer
2. Target Contextual Answer vs Generated Contextual Answer

Provide similarity scores as percentages. Do not give 0% directly - if the values are close, provide percentage according to that similarity.

Format your response exactly as:
Contextual Answer similarity: [Value in %]
Parametric Answer similarity: [Value in %]
'''

        # Generate response using Azure OpenAI
        response = client.chat.completions.create(
            model="gpt-4.1",  # Use GPT-4.1 as requested
            messages=[
                {"role": "system", "content": "You are an expert evaluator comparing Bengali text answers for semantic similarity."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.1,
            max_tokens=500
        )
        
        result = response.choices[0].message.content

        # Extract similarity scores from the response
        contextual_similarity = ""
        parametric_similarity = ""
        
        for line in result.splitlines():
            if "Contextual Answer similarity:" in line:
                contextual_similarity = line.split(":")[-1].strip()
            elif "Parametric Answer similarity:" in line:
                parametric_similarity = line.split(":")[-1].strip()

        return {
            "Contextual": contextual_similarity,
            "Parametric": parametric_similarity
        }
        
    except Exception as e:
        print(f"Error processing row: {e}")
        return {"Contextual": "", "Parametric": ""}

# Load the CSV file
print("Loading CSV file...")
df = pd.read_csv('parametricllama.csv')

# Add new columns for similarity scores
df['Contextual Similarity'] = ""
df['Parametric Similarity'] = ""

# Process each row and calculate similarity with progress bar
print("Starting evaluation process...")
for idx in tqdm(range(0, len(df)), desc="Processing rows", unit="row"):
    row = df.iloc[idx]
    
    # Calculate similarity scores
    similarity_scores = calculate_similarity(row)
    
    # Skip this iteration if similarity_scores is None
    if similarity_scores is None:
        continue
    
    # Update the DataFrame with similarity scores
    df.at[idx, 'Contextual Similarity'] = similarity_scores['Contextual']
    df.at[idx, 'Parametric Similarity'] = similarity_scores['Parametric']

    # Save after every 10 rows to avoid data loss
    if idx % 10 == 0:
        df.to_csv('processed_factual_llama_results.csv', index=False)
        print(f"Progress saved at row {idx}")

    # Rate limiting to comply with API usage policies
    time.sleep(2)  # Adjust timing as needed for Azure OpenAI limits

# Final save
df.to_csv('processed_factual_llama_results.csv', index=False)
print("Processing completed. Results saved to 'processed_factual_llama_results.csv'")

# Print summary statistics
print("\nSummary Statistics:")
print(f"Total rows processed: {len(df)}")
print(f"Rows with contextual similarity: {len(df[df['Contextual Similarity'] != ''])}")
print(f"Rows with parametric similarity: {len(df[df['Parametric Similarity'] != ''])}")
